#ifndef CONFIG_DEBUG_MACRO_H
#define CONFIG_DEBUG_MACRO_H

#define PRINT_PREFIX 0
#define PRINT_CURRENT_TRACE 0
#define PRINT_FORMULA 0
#define CHECK_BUILD 0
#define PRINT_BRANCH_INFO 1

#endif // CONFIG_DEBUG_MACRO_H